### ISSUE TITLE
emp run: fatal error: newosproc

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#1077]
Not 100% sure how to reproduce this, but we've seen it a few times today in our staging environment.  Not sure why it happened earlier in the day, but just now I was rolling out a new AMI, and tried an emp run at the same time (the controllers had finished, the minions were still rolling out).  The emp run was hanging for a while, and when I tracked down the task in the dashboard I looked at the instance it was launching on.  That instance had a ton of tasks in pending mode, and the network was being hammered (pulling down images for all those tasks is my guess).  Anyway, after enough time, I got this:

```
# emp_stage run -a r101-api bash
A commit message is required, enter one below:
> testing new ami
Attaching to task/e4b703f0-95cc-4c4d-8023-f78f5075d679...
runtime: failed to create new OS thread (have 2 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

runtime stack:
runtime.throw(0x896b2a, 0x9)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc420040000, 0xc42004ffc0)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x8d81e8, 0x0)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/proc.go:1572 +0x132
runtime.main.func1()
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/proc.go:126 +0x36
runtime.systemstack(0xaeb100)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/asm_amd64.s:252 fp=0xc42003a768 sp=0xc42003a760
runtime.main()
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/proc.go:127 +0x6c fp=0xc42003a7c0 sp=0xc42003a768
runtime.goexit()
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42003a7c8 sp=0xc42003a7c0
```

**Comment by phobologic** [comment]
I think I've narrowed this down to being an issue specific to our docker environment, where we're using `--userns-remap=default` on the docker daemon, and for some reason the mapped user only ends up with a process limit of 512 - and since the process limit is the same for a single user, and is not container specific, this was leading us to running out of available processes.
