### ISSUE TITLE
EOF when running requests against `ecs` processes

### ISSUE THREAD

**Issue by mhahn** [remind101/empire#885]
During upgrading empire on dev, I tore down the minion cluster to start from scratch, so no process are running on the minion currently.

I'm running empire version: `remind101/empire:b836b09383b94ec45dc0ad087b8221d7a035978e`

`emp info` and `emp env` are working correctly.

Anything that touches the scheduler (`emp ps`, `emp scale`, `emp restart`) returns an `EOF` error.

`emp ps` is panicking with:

```
2016/06/20 17:40:00 http: panic serving 10.128.1.253:44425: runtime error: invalid memory address or nil pointer dereference
goroutine 82 [running]:
net/http.(*conn).serve.func1(0xc820533550, 0x7f76c6d88428, 0xc82002a0e0)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/remind101/empire/scheduler/cloudformation.(*MigrationScheduler).backend(0x0, 0xc82042b740, 0x24, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/scheduler/cloudformation/migration.go:83 +0x119
github.com/remind101/empire/scheduler/cloudformation.(*MigrationScheduler).Backend(0x0, 0xc82042b740, 0x24, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/scheduler/cloudformation/migration.go:65 +0x60
github.com/remind101/empire/scheduler/cloudformation.(*MigrationScheduler).Instances(0x0, 0x7f76c6d97d00, 0xc82042b050, 0xc82042b740, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/scheduler/cloudformation/migration.go:184 +0x6b
github.com/remind101/empire/scheduler.(*AttachedRunner).Instances(0xc8202f0ea0, 0x7f76c6d97d00, 0xc82042b050, 0xc82042b740, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:7 +0xb1
github.com/remind101/empire.(*tasksService).Tasks(0xc82002a5d8, 0x7f76c6d97d00, 0xc82042b050, 0xc82026ed70, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/tasks.go:29 +0xd1
github.com/remind101/empire.(*Empire).Tasks(0xc820116000, 0x7f76c6d97d00, 0xc82042b050, 0xc82026ed70, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/empire.go:326 +0x6d
github.com/remind101/empire/server/heroku.(*GetProcesses).ServeHTTPContext(0xc82002a858, 0x7f76c6d97d00, 0xc82042b050, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/heroku/processes.go:51 +0xf1
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.(*handler).ServeHTTPContext(0xc8202cf910, 0x7f76c6d97d00, 0xc82042b050, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	<autogenerated>:9 +0x9a
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.(*Router).ServeHTTPContext(0xc8202f1e00, 0x7f76c6d97d00, 0xc82042b050, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/router.go:106 +0x44d
github.com/remind101/empire/server/heroku.(*Authentication).ServeHTTPContext(0xc8202d2d20, 0x7f76c6d97d00, 0xc82042af60, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/heroku/authentication.go:69 +0x9c1
github.com/remind101/empire/server/heroku.New.func1(0x7f76c6d97d00, 0xc82042ad50, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/heroku/heroku.go:80 +0x80
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.HandlerFunc.ServeHTTPContext(0xc8202d2d40, 0x7f76c6d97d00, 0xc82042ad50, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/httpx.go:25 +0x5a
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.(*handler).ServeHTTPContext(0xc8201b9d10, 0x7f76c6d97d00, 0xc82042ad50, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	<autogenerated>:9 +0x9a
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.(*Router).ServeHTTPContext(0xc8202f1de0, 0x7f76c6d97d00, 0xc82042ad50, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/router.go:106 +0x44d
github.com/remind101/empire/server/middleware.LogRequests.func1(0x7f76c6d97d00, 0xc82042ac60, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/middleware/middleware.go:48 +0x2e7
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.HandlerFunc.ServeHTTPContext(0xc8202d2e60, 0x7f76c6d97d00, 0xc82042ac60, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/httpx.go:25 +0x5a
github.com/remind101/empire/server/middleware.PrefixRequestID.func1(0x7f76c6d97d00, 0xc82042ac60, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/middleware/middleware.go:65 +0x518
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.HandlerFunc.ServeHTTPContext(0xc8202d2e80, 0x7f76c6d99940, 0xc82042abd0, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/httpx.go:25 +0x5a
github.com/remind101/empire/server/middleware.(*Recovery).ServeHTTPContext(0xc8201b9f40, 0x7f76c6d99940, 0xc82042abd0, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/middleware/recovery.go:43 +0xfa
github.com/remind101/empire/server/middleware.WithRequest.func1(0x7f76c6d99940, 0xc82042abd0, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/middleware/request.go:23 +0x17b
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.HandlerFunc.ServeHTTPContext(0xc8202d2ea0, 0x7f76c6d97d00, 0xc82031c870, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/httpx.go:25 +0x5a
github.com/remind101/empire/server/middleware.Handler.func1(0x7f76c6d99908, 0xc820533760, 0xc82009a9a0)
	/go/src/github.com/remind101/empire/server/middleware/middleware.go:17 +0x6f
net/http.HandlerFunc.ServeHTTP(0xc8202ae4b0, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc8202e11a0, 0x7f76c6d99908, 0xc820533760, 0xc82009a9a0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820533550)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

`emp restart` is panicking with:

```
2016/06/20 17:40:51 http: panic serving 10.128.1.253:44444: runtime error: invalid memory address or nil pointer dereference
goroutine 84 [running]:
net/http.(*conn).serve.func1(0xc8201b5600, 0x7f76c6d88428, 0xc82002a680)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/remind101/empire/scheduler/cloudformation.(*MigrationScheduler).backend(0x0, 0xc82021f8c0, 0x24, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/scheduler/cloudformation/migration.go:83 +0x119
github.com/remind101/empire/scheduler/cloudformation.(*MigrationScheduler).Submit(0x0, 0x7f76c6d97d00, 0xc82029bc50, 0xc8203ee480, 0x0, 0x0)
	/go/src/github.com/remind101/empire/scheduler/cloudformation/migration.go:94 +0x60
github.com/remind101/empire/scheduler.(*AttachedRunner).Submit(0xc8202f0ea0, 0x7f76c6d97d00, 0xc82029bc50, 0xc8203ee480, 0x0, 0x0)
	<autogenerated>:13 +0x7d
github.com/remind101/empire.(*releasesService).Release(0xc82002a5f0, 0x7f76c6d97d00, 0xc82029bc50, 0xc8200ff200, 0x0, 0x0)
	/go/src/github.com/remind101/empire/releases.go:139 +0x79
github.com/remind101/empire.(*releasesService).ReleaseApp(0xc82002a5f0, 0x7f76c6d97d00, 0xc82029bc50, 0xc820108280, 0xc8202608c0, 0x0, 0x0)
	/go/src/github.com/remind101/empire/releases.go:157 +0x19d
github.com/remind101/empire.(*appsService).Restart(0xc82002a5a8, 0x7f76c6d97d00, 0xc82029bc50, 0xc820108280, 0xc820397240, 0xc8202608c0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/remind101/empire/apps.go:132 +0xe2
github.com/remind101/empire.(*Empire).Restart(0xc820116000, 0x7f76c6d97d00, 0xc82029bc50, 0xc820397240, 0xc8202608c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/remind101/empire/empire.go:366 +0x1fb
github.com/remind101/empire/server/heroku.(*DeleteProcesses).ServeHTTPContext(0xc82002a898, 0x7f76c6d97d00, 0xc82029bc50, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/heroku/processes.go:163 +0x3e7
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.(*handler).ServeHTTPContext(0xc8202c8840, 0x7f76c6d97d00, 0xc82029bc50, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	<autogenerated>:9 +0x9a
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.(*Router).ServeHTTPContext(0xc8202f1e00, 0x7f76c6d97d00, 0xc82029bc50, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/router.go:106 +0x44d
github.com/remind101/empire/server/heroku.(*Authentication).ServeHTTPContext(0xc8202d2d20, 0x7f76c6d97d00, 0xc82029bb60, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/heroku/authentication.go:69 +0x9c1
github.com/remind101/empire/server/heroku.New.func1(0x7f76c6d97d00, 0xc82029b950, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/heroku/heroku.go:80 +0x80
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.HandlerFunc.ServeHTTPContext(0xc8202d2d40, 0x7f76c6d97d00, 0xc82029b950, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/httpx.go:25 +0x5a
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.(*handler).ServeHTTPContext(0xc8201b9d10, 0x7f76c6d97d00, 0xc82029b950, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	<autogenerated>:9 +0x9a
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.(*Router).ServeHTTPContext(0xc8202f1de0, 0x7f76c6d97d00, 0xc82029b950, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/router.go:106 +0x44d
github.com/remind101/empire/server/middleware.LogRequests.func1(0x7f76c6d97d00, 0xc82029b890, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/middleware/middleware.go:48 +0x2e7
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.HandlerFunc.ServeHTTPContext(0xc8202d2e60, 0x7f76c6d97d00, 0xc82029b890, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/httpx.go:25 +0x5a
github.com/remind101/empire/server/middleware.PrefixRequestID.func1(0x7f76c6d97d00, 0xc82029b890, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/middleware/middleware.go:65 +0x518
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.HandlerFunc.ServeHTTPContext(0xc8202d2e80, 0x7f76c6d99940, 0xc82029b800, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/httpx.go:25 +0x5a
github.com/remind101/empire/server/middleware.(*Recovery).ServeHTTPContext(0xc8201b9f40, 0x7f76c6d99940, 0xc82029b800, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/middleware/recovery.go:43 +0xfa
github.com/remind101/empire/server/middleware.WithRequest.func1(0x7f76c6d99940, 0xc82029b800, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/server/middleware/request.go:23 +0x17b
github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx.HandlerFunc.ServeHTTPContext(0xc8202d2ea0, 0x7f76c6d97d00, 0xc82031c870, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180, 0x0, 0x0)
	/go/src/github.com/remind101/empire/vendor/github.com/remind101/pkg/httpx/httpx.go:25 +0x5a
github.com/remind101/empire/server/middleware.Handler.func1(0x7f76c6d99908, 0xc8201b56b0, 0xc820537180)
	/go/src/github.com/remind101/empire/server/middleware/middleware.go:17 +0x6f
net/http.HandlerFunc.ServeHTTP(0xc8202ae4b0, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc8202e11a0, 0x7f76c6d99908, 0xc8201b56b0, 0xc820537180)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8201b5600)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

In the database I see that the processes have been correctly defaulted to the `ecs` backend:

```
empire=> select * from scheduler_migration;
                app_id                | backend
--------------------------------------+---------
 df9a767e-112a-46df-b5ba-a7dc2feec3eb | ecs
 fa832979-9ace-4009-b22c-c351650b3bc7 | ecs
 7212a3a7-74a5-4dab-ac3e-e5a6fdd67d75 | ecs
````

**Comment by mhahn** [comment]
This was because there was an error creating the CF scheduler, `ZoneID` wasn't provided, but https://github.com/remind101/empire/blob/master/cmd/empire/factories.go#L107 doesn't return the error

**Comment by mhahn** [comment]
https://github.com/remind101/empire/pull/887/files makes the error reporting better
